config/routes.rb
BlakeHilscherCa::Application.routes.draw do
  
  mount Ckeditor::Engine => '/ckeditor'

  root :to => 'pages#home'
  
  match 'home' => 'pages#home'
  
  devise_for :users
  
  resources :posts, :only => [:index, :show]
  
  namespace :admin do
    root :to => 'pages#dashboard'
    resources :posts
  end
  

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.admin?
      can :manage, :all
    else
      can :read, :all
    end
    
    # Define abilities for the passed in user here. For example:
    #
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
              
  delegate :url, :current_path, :size, :content_type, :filename, :to => :data
  
  validates_presence_of :data
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  mount_uploader :data, CkeditorAttachmentFileUploader, :mount_on => :data_file_name
	
	def url_thumb
	  @url_thumb ||= Ckeditor::Utils.filethumb(filename)
	end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, :mount_on => :data_file_name
	
	def url_content
	  url(:content)
	end
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :content, :title
  belongs_to :user  
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable
  attr_accessible :email, :password, :password_confirmation, :remember_me
  
  ROLES = %w[admin user]
    
  has_many :posts
    
  def admin?
    self.role == 'admin'
  end
    
  def user?
    self.role == 'user'
  end
  
end

app/controllers/admin/pages_controller.rb
class Admin::PagesController < AdminController
  def dashboard
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < AdminController
  load_and_authorize_resource
  
  def index
    respond_with @posts = current_user.posts.order(:created_at).page(params[:page])
  end

  def show
    respond_with @post = current_user.posts.find(params[:id])
  end

  def new
    respond_with @post = current_user.posts.new
  end

  def edit
    respond_with @post = current_user.posts.find(params[:id])
  end

  def create
    @post = current_user.posts.new(params[:post])
    
    if @post.save
      redirect_to edit_admin_post_url(@post)
    else
      respond_with @post
    end
  end
  
  def update
    @post = current_user.posts.find(params[:id])
    @post.update_attributes(params[:post])
    respond_with @post, :location => edit_admin_post_url
  end

  def destroy
    @post = current_user.posts.find(params[:id])
    @post.destroy
    respond_with @post, :location => admin_posts_url
  end
  
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_filter :authenticate_user!
  layout 'admin'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  respond_to :html, :json
  
  rescue_from CanCan::AccessDenied do |exception|
    flash[:error] = exception.message
    redirect_to root_url
  end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    respond_with @posts = Post.order(:created_at).page(params[:page]).per(5)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  def index
    respond_with @posts = Post.order(:created_at).page(params[:page]).per(5)
  end

  def show
    respond_with @post = Post.find(params[:id])
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  def controller_and_action_eql(controller, action)
    controller_eql(controller) && action_eql(action)
  end
  def controller_eql(controller)
    controller_name == controller.to_s
  end
  def action_eql(action)
    action_name == action.to_s
  end
end

app/views/admin/_nav.html.haml
%nav.admin
  %ul
    %li= link_to 'Admin Dashboard', admin_root_path
    %li= link_to 'Manage Posts', admin_posts_path
    %li= link_to "Manage Account", edit_user_registration_path    
    %li= link_to "Sign Out", destroy_user_session_path, :method => :delete

app/views/admin/pages/dashboard.html.haml
%h2 Admin Dashboard
= link_to 'Manage Posts', admin_posts_path

app/views/admin/posts/_form.html.haml
= simple_form_for [:admin, post], :html => { :class => 'form-horizontal' } do |f|
  %fieldset
    %legend= "#{controller.action_name.capitalize} Post"
    
    = f.input :title
    = f.input :content, :as => :ckeditor, :input_html => { :toolbar => 'Full' }
    
    .form-actions
      = f.submit nil, :class => 'btn btn-primary'
      = link_to 'Cancel', admin_posts_path, :class => 'btn'

app/views/admin/posts/_links.html.haml
%nav.admin-posts
  %ul
    - unless controller_and_action_eql :posts, :new
      %li= link_to "Create New Post", new_admin_post_path
      
    - unless controller_and_action_eql :posts, :index
      %li= link_to "View All Posts", new_admin_post_path

app/views/admin/posts/_posts.html.haml
.collection.collection-admin_posts
  %ul
    %li.collection-record.collection-header
      .inner-record
        .record-column.post-title
          .inner-column Title
        .record-column.post-content
          .inner-column Content
        .record-column.post-actions
          .inner-column Manage
          
    - posts.each do |post|
      %li.collection-record{:id => "record-#{post.id}", :data => {:id => post.id}}
        .inner-record
          .record-column.post-title
            .inner-column= post.title
          .record-column.post-content
            .inner-column= truncate(post.content, :length => 200, :omission => "...")
          .record-column.record-actions
            .inner-column
              = link_to "Edit Post", edit_admin_post_path(post)
              = link_to 'Destroy', admin_post_path(post), :confirm => 'Are you sure?', :method => :delete, :class => 'record-destroy'
              
  = paginate posts

app/views/admin/posts/edit.html.haml
= render 'form', :post => @post

app/views/admin/posts/index.html.haml
%h2 Posts

= render 'posts', :posts => @posts
= render 'links'

app/views/admin/posts/new.html.haml
= render 'form', :post => @post

app/views/admin/posts/show.html.haml
= render 'form', :post => @post

app/views/application/_chromeframe.html.haml
-# Prompt IE 6 users to install Chrome Frame. Remove this if you support IE 6.
-# chromium.org/developers/how-tos/chrome-frame-getting-started
/[if lt IE 7 ]
  %p.chromeframe
    Your browser is <em>ancient!</em>
    <a href="http://browsehappy.com/">Upgrade to a different browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">install Google Chrome Frame</a> to experience this site.

app/views/application/_flashes.html.haml
#flash
  - flash.each do |key, value|
    .wrapper
      %div{ :title => key.to_s.humanize, :class => "#{key}-message" }
        %p= value

app/views/application/_footer.html.haml
%footer.application
  .inner-footer-application
    %small.copyright
      Blake Hilscher Ca, Copyright &copy; #{ Date.today.year }

app/views/application/_head.html.haml
%head
  %meta{ :charset => "utf-8" }/

  -# Use the .htaccess and remove these lines to avoid edge case issues.
  -# More info: h5bp.com/b/378
  %meta{ 'http-equiv' => 'X-UA-Compatible', :content => 'IE=edge,chrome=1' }/

  %title
    == #{ controller.controller_name.titleize } - #{ controller.action_name.titleize }

  %meta{ :name => "description", :content => "" }/

  -# Mobile viewport optimized: h5bp.com/viewport
  %meta{ :name => "viewport", :content => "width=device-width" }/

  -# Place favicon.ico and apple-touch-icon.png in the root directory: mathiasbynens.be/notes/touch-icons

  = render "stylesheets"

  -# More ideas for your <head> here: h5bp.com/d/head-Tips

  -# All JavaScript at the bottom, except polyfills
  = javascript_include_tag "polyfills"

  = csrf_meta_tag

app/views/application/_header.html.haml
%header.application
  = render 'admin/nav' if user_signed_in?    
  .inner-header-application
    %h1.brand-application= link_to "Blake Hilscher, Developer & Ruby Enthusiast", root_path, :class => 'brand-blakehilscher'
    
    %nav.application
      %ul
        %li.nav-active= link_to 'Blog', "/#about"
        %li= link_to 'Code', 'https://github.com/blakehilscher/', :target => :blank
        %li= link_to 'Contact', "/#contact"

app/views/application/_javascripts.html.haml
= javascript_include_tag "application"

-#  Append your own using content_for :javascripts
= yield :javascripts

-# asynchronous google analytics: mathiasbynens.be/notes/async-analytics-snippet
-# Looks for google_account_id first in ENV['GOOGLE_ACCOUNT_ID'] then in config/html5_rails.yml
- if !google_account_id.blank?
  :javascript
    var _gaq=[['_setAccount','#{ google_account_id }'],['_trackPageview']];
    (function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
    g.src=('https:'==location.protocol?'//ssl':'//www')+'.google-analytics.com/ga.js';
    s.parentNode.insertBefore(g,s)}(document,'script'));

app/views/application/_stylesheets.html.haml
= stylesheet_link_tag 'application', :media => nil

-# Append your own using content_for :stylesheets
= yield :stylesheets

app/views/layouts/admin.html.haml
!!! 5
-# http://paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither
- html_tag :class => "no-js", :lang => "en" do
  = render "application/head"
  = render "application/javascripts"
  
  %body{ :class => "#{ controller.controller_name }" }
    = render "application/chromeframe"
    
    #container
      = render "application/header"
      
      #main{:role => "main"}
        = render "application/flashes"

        #content{:class => "#{'with-aside_main' if content_for? :aside_main}"}
          .inner-content= yield
          
        - if content_for? :aside_main
          %aside.main
            .inner-aside-main= yield :aside_main
      
      = render "application/footer"

app/views/layouts/application.html.haml
!!! 5
-# http://paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither
- html_tag :class => "no-js", :lang => "en" do
  = render "head"

  %body{ :class => "#{ controller.controller_name }" }
    = render "chromeframe"
    
    #container
      = render "header"
      
      #main{:role => "main", :class => "#{'with-aside_main' if content_for? :aside_main}"}
        = render "flashes"

        #content
          .inner-content= yield
          
        - if content_for? :aside_main
          %aside.main
            .inner-aside-main= yield :aside_main
      
      = render "footer"

    -# Javascript at the bottom for fast page loading
    = render "javascripts"

app/views/pages/_about.html.haml
%section.about
  .inner-section-about
    
    .photograph
      .inner-photograph= image_tag 'http://www.gravatar.com/avatar/b0b2e5b7aa788c536aa50e25ac3fe1a9.png?s=200'
    
    .about-content
      %p I'm Blake Hilscher and this is my development blog where I talk about ruby, javascript, and other geeky endeavors.
  
    .collection-social_media
      %ul
        %li= link_to "LinkedIn", 'http://www.linkedin.com/pub/blake-hilscher/20/56a/902', :target => :blank
        %li= link_to "Github", 'https://github.com/blakehilscher/', :target => :blank
        %li= link_to "Twitter", 'http://twitter.com/#!/blakehil', :target => :blank

app/views/pages/home.html.haml
= render 'posts/posts', :posts => @posts

- content_for :aside_main do
  = render 'about'

app/views/posts/_post.html.haml
.post
  .post-title
    %h2= post.title
  .post-content= post.content.html_safe

app/views/posts/_posts.html.haml
.collection-posts
  %ul
    - posts.each do |post|
      %li.post.collection-record{:id => "record-#{post.id}", :data => {:id => post.id}}
        .inner-record
          .record-column.post-title
            .inner-column
              %h3= post.title
          .record-column.post-content
            .inner-column= truncate(post.content, :length => 500).html_safe
            
          .record-column.post-actions
            .inner-column
              = link_to "Read More", post_path(post), :class => 'post-show'
              
  = paginate posts

app/views/posts/show.html.haml
= render 'posts/post', :post => @post

- content_for :aside_main do
  = render 'pages/about'